---
title: "Study_plan"
output:
  html_document:
    df_print: paged
  pdf_document: default
  word_document: default
bibliography: citations.bib
---

#Introduction
Defined as physical injury and the body´s consequential response, trauma, is one of the leading causes of mortality and morbidity in all age groups worldwide.[@david2021] In many cases the outcome is mostly dependent on the quality of care acquired.[@Dogrul2020] According to the American College of Surgeons Committee, the decreased amount of immediate, early and late deaths is due to advances in trauma care. For instance, the application of standardized training, improvement of prehospital care and dedicated trauma teams [Committee]. This illustrates the importance of trauma care and why further advancements are essential.

Trauma is the leading cause of mortality in people below the age of 44 and the fourth in all age groups [@champion1990]. Approximately 5.8 million die each year due to trauma. Motor vehicle crashes alone stands for an estimated 20 to 50 million annually [Committee]. With an average of more than 7 days in the hospital each stay [@champion1990], it is one of the most prevalent reasons for admission.


#References
