---
title: "Study plan"
output:
#  word_document: default
 # pdf_document: default
bibliography: citations.bib
csl: bmcemerg.csl
link-citations: yes

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Introduction

Defined as physical injury and the body´s consequential response, trauma, is one of the leading causes of mortality and morbidity in all age groups and the leading cause of mortality in people below the age of 44 [@David2021] [@champion1990]. Approximately 5.8 million people die each year due to trauma. Motor vehicle crashes alone stand for more than one million deaths and roughly between 20 and 50 million injuries annually [@Committee2013]. With an average of more than 7 days in the hospital each stay [@champion1990], it is one of the most prevalent reasons for admission. In 2020 road traffic accidents were third in disease burden worldwide, measured by Disability-Adjusted Life Years (DALY),  a term used to describe the impact of health problems and to measure the significance of improvement in medical care [@Murray1996],[@Haagsma2015]. <!--Snyggt, ev småpill men låt Martin tycka till isf -->

In many cases the outcome is mostly dependent on the quality of care acquired [@Dogrul2020]. In a teaching hospital in Tehran, reviews of all trauma cases in 1 year displayed inappropriate care in 45% of all deaths and implied that approximately 26% of all trauma deaths were preventable [@Zafarghandi2003]. <!--Korrekt, försök hitta flera källor och gärna någon review. preventable death rate brukar variera mellan isch 10%-80% beroende på kontext -->Preventable death panels aim to decrease the amount of preventable deaths by investigating common factors between the cases [@Jung2019]. Airway management, inadequate chest compression, inadequate blood or fluid supply are some factors that previously were found in need of improvement in trauma care [@Zafarghandi2003],[@Maio1996]. Such advances in trauma care are the leading cause of the decreased amount of preventable deaths according to the American College of Surgeons Committee [@Committee2013]. <!--Bra! Ev lite ytterligare källor och därmed mindre justeringar på varje påstående för formalian. -->

It has always <!--Undvik så definitiva termer som "always", bättre att säga exv "Its historically been importan to"... --> been of great importance to investigate factors that can be improved in trauma care and different methods are used to do so. The gold standard being mortality and morbidity (M&M) conferences, also known as deaths and complications reviews. <!--Försök hålla dig till en terminologi för att beskriva dessa reviews, nu är det MoM, Deaths and complications..., preventable death rate panel osv.  -->Some cases get selected for review to further investigate the reason behind the mortality or morbidity [@WHO2009]. The results are used to improve the trauma care and to decrease the amount of preventable errors. Although the selection of patients is a vital part of these conferences, it remains a process that requires a great amount of resources and is still complicated to this day due to the lack of studies on the subject.
<!--Se över sista meningens formulering, Beskriv mer att hela processen är resurskrävande. -->
Despite the evidence supporting the use of predefined models for case selection, there is limited data on specific factors associated with opportunities for improvement in trauma care [@Slater2020]. Therefore methods such as audit filters are adopted in trauma quality improvement programs. Audit filters are predefined factors used in the selection of cases for review and represent an unfavorable alternation, proclaimed leading to a disadvantageous outcome [@WHO2009],[@Evans2009]. Set audit filters are for instance systolic blood pressure under 90, Glasgow Coma Scale less than 9 and not intubated, time to acute intervention more than 60 minutes and a few more. A systematic review of audit filters in 2009 found no studies meeting set criteria determining the effectiveness of set audit filters [@Evans2009]. <!--Snyggt, lite småpill men tycker martin ska få tyckatill innan vi kör detaljer -->

To this day trauma quality improvement programs rely on set filters for the selection of cases for M&M conferences. Some studies have found no major opportunities for improvement in currently used audit filters and believe further advancements are essential [@Cryer1996],[@Copes1995]. We hypothesize that the selection of cases for multidisciplinary mortality and morbidity reviews can be refined by the usage of other factors. We aim therefore to find factors associated with opportunities for improvement in trauma care for later development of models trained to identify cases with capacity for improvement. This can be investigated by the examination of many other factors registered in our database.

# Methods

### Study design

We conducted a retrospective cohort study using data from the Karolinska University Hospital trauma registry and the trauma care quality database. The trauma care quality database consists of the cases selected for review and the presence of opportunity for improvement is noted. The registers where linked and possible associated factors regardin possible association with opportunities for improvement were extracted. All statistical analysis was firstly done one randomized data to insure objectivity. Bivariate and multivariable logistic regression was used to determine significant correlation with the presense of oportunity for improvement. 

### Setting

In Sweden, prehospital care is managed by paramedics and specialy trainded physicians. When stabilized, trauma patients are transported to hospitals with dedicated trauma teams and sufficient competence. These teams consist of a trauma surgeon, an anesthetist, an orthopedic surgeon, a radiologist and specialized nurses. Karolinska University Hospital in Solna is a level one trauma center, with direct access to radiology, operation, intensve care interventions [@Social2015],[@NKS2020].

All data used in this study is provided from the mentioned databases. The trauma care quality database includes opportunities for improvement as the main outcome and is defined as yes or no, identified by multidisciplinary review boards. Many other factors from the databases are included and examined.

<!--Jag ändrade och skrev ihop "settings" till Elias, se nedan. låna valfritt därifrån. Behöver inte vara så långt.: 

Karolinska University Hospital is a level 1 trauma centre that manages 1300 trauma patients each year. Trauma patients are triaged in a pre-hospital setting as a priority one or two by assessing vital physiological parameters, anatomical criterias and mechanisms of injury. The pre-hospital system includes a helicopter emergency medical service and three  physcician staffed ambulances. The in-hospital system includes a multidisciplinary trauma team with a surgeon,an anesthesiologist, an orthopedic surgeon, a radiologist, a surgical nurse, an assistant surgical nurse, a nurse anesthetist, an emergency medicine nurse, an emergency medicine assistant nurse and a radiology nurse. Consultations and involvement with associated specializes are available around the clock. The team has immediate access to radiology, surgery, and intensive care.

The multidisciplinary review meetings regarding opportunity for improvement, selects patients from the trauma registry using audit filters. The cases are then discussed during monthly meetings which a board of representatives from all disciplines involved in trauma care - surgery, neurosurgery, orthopaedics, anaesthesia and intensive care, nursing, and radiology. The meeting reach consensus regarding the presence of opportunities for improvement and appropriate corrective actions. Follow up is conducted after 30 days and registers survival, days on ventilator, GCS at discharge, highest level of care received, location of discharge, if there were a transfer to another unit of care and if there was an autopsy performed as well as 15 hospital specific variables.-->

### Participants

We included all trauma patients included in the Karolinska care quality registry between 2014 and 2021. All patients where originally from the Karolinska University Hospital trauma registry which consecutively includes all patients aged at least 15 years admitted with trauma team activation, regardless of injury severity score, as well as patients admitted without trauma team activation but found to have an injury severity score of more than 9. Selection for the Karolinska care quality registry and the associated multidisciplinary mortality and morbidity review is done using audit filters: systolic blood pressure less than 90, Glasgow coma scale less than 9 and not intubated, injury severity score more than 15 but not admitted to the intensive care unit, time to acute intervention more than 60 minutes, time to computed tomography more than 30 minutes, and death within 30 days after trauma. We did a complete case analysis, hence missing data in any of the covariates or outcome resulted in exclusion. 

### Variables

**Study outcome**

The study outcome will be significant association to the outcome variable using any or all predictive variables. The outcome variable is the presence of opportunities for improvement, as labelled by the mortality and morbidity review board, and defined as a binary variable with the levels "Yes - At least one opportunity for improvement identified" and "No - No opportunities for improvement identified". Data on this outcome will be extracted from the trauma care quality database. 

**Predictors**
<!--Beskriv kort, nästan lista, de olika variablerna. Kommentera om de hanteras som Kvalitativa eller kontinuerliga -->
Since our aim is to identify factors associated with improvement in trauma care, the database used will therefore have some factors that can be further examined. The information registered in the database is divided into sections. First of all the transportation is included, the time taken from reported trauma until the patient arrives at the hospital. Demographics, including age and gender. Vital signs such as blood pressure, respiratory rate, saturation, pulse, temperature and also Glasgow coma scale upon arrival. The types of injuries acquired and the mechanism of the trauma. Procedures performed on the patient are also included and many more [@Swetrau2020].

### Data sources and measurements
<!--Egentligen bara nämna kort att all data kommer från de två registren. -->
All of the data is extracted from the Karolinska University Hospital trauma registry and the trauma care quality database. Age and gender are collected from the patients personal number. Vital signs are measured on arrival to the emergency department by staff and the other variables get registered from the patients charts. 

### Bias

We will use simulated data to develop the analysis model and after satisfactory results implement it on the data collected from the databases. A selection biased, caused by the inclusion criteria for the Karolinska care quality registry and the trauma registry, is possible.

### Study size

We will include all patients the from the Karolinska University Hospital trauma care quality registry  and the corresponding information from the Karolinska University Hospital trauma registry. Registration took place between 2014 and 2021 with about 2200 patients.

### Quantitive variables
<!-- är mallen bara för quantitativa variabler? Inte kvalitativa? -->
Such variable include vital signs. Pulse, Blood pressure, temperature and respiratory rate. Glasgow coma scale as previously described. All registered to the databases.

### Statistical methods

We did a complete case analysis of all patients in the Karolinska trauma care quality registry. Variables was handled and converted in accordance with the SweTrau Manual. Potential variables was selected based on currently used audit filters, expert consensus and common demographics. Bivariate and multivariable logistic regression was used to determine significant correlation with the presense of oportunity for improvement. A p value of less then 0,05 was considered significant.

# References
